version = 1
SPDX-PackageName = "zbrett"
SPDX-PackageSupplier = "protagx <hello@protagx.com>"
SPDX-PackageDownloadLocation = "git@bitbucket.org:precisyn/zbrett.git"

[[annotations]]
path = [
  "**/*.toml", "**/*.cfg", "**/*.ini", "**/*.json", "**/*.yml", "**/*.yaml",
  "**/*.md", "**/*.txt", "**/.gitignore", "**/.gitattributes", "**/.editorconfig",
  ".python-version", "CODEOWNERS", "**/*.service", "**/*.mmd", "**/*.psd1", "**/*.ps1",
  "**/*.env.example", "**/py.typed",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 protagx <hello@protagx.com>"
SPDX-License-Identifier = "EUPL-1.2"
